import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedstart_screenwidget/generated/GeneratedFlash_screenWidget.dart';

/* Component start_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStart_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedWelcome_screen1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 640.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 360.0,
                        height: 640.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width = constraints.maxWidth;

                                  final double height = constraints.maxHeight;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: 0,
                                        y: 0,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedFlash_screenWidget(),
                                        ))
                                  ]);
                                }),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
