import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedMenu2Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedSearch_toolWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget2.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget4.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget1.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedStatusbarWidget7.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedsearchwidget1/generated/GeneratedIphonekeyboard1Widget2.dart';

/* Component search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 662.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 360.0,
                              height: 640.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 247, 247, 247),
                                      ),
                                    ),
                                    Positioned(
                                      left: 172.0,
                                      top: 549.0,
                                      right: null,
                                      bottom: null,
                                      width: 66.0,
                                      height: 44.0,
                                      child: GeneratedRectangle25Widget(),
                                    ),
                                    Positioned(
                                      left: -12.0,
                                      top: 538.0,
                                      right: null,
                                      bottom: null,
                                      width: 384.0,
                                      height: 124.0,
                                      child: GeneratedMenu2Widget(),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 360.0,
                                      height: 186.0,
                                      child: TransformHelper.translate(
                                          x: 0.00,
                                          y: -221.00,
                                          z: 0,
                                          child: GeneratedRectangle19Widget()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 368.0,
                                      height: 290.0,
                                      child: TransformHelper.translate(
                                          x: -4.00,
                                          y: 175.00,
                                          z: 0,
                                          child:
                                              GeneratedIphonekeyboard1Widget2()),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 339.0,
                height: 32.0,
                child: TransformHelper.translate(
                    x: -0.50,
                    y: -239.00,
                    z: 0,
                    child: GeneratedSearch_toolWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: TransformHelper.translate(
                    x: -114.00,
                    y: -193.36,
                    z: 0,
                    child: GeneratedBuuton2Widget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: TransformHelper.translate(
                    x: 5.00,
                    y: -193.36,
                    z: 0,
                    child: GeneratedBuuton2Widget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: TransformHelper.translate(
                    x: 124.00,
                    y: -193.36,
                    z: 0,
                    child: GeneratedBuuton2Widget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: TransformHelper.translate(
                    x: -86.00,
                    y: -155.36,
                    z: 0,
                    child: GeneratedBuuton2Widget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: TransformHelper.translate(
                    x: 31.00,
                    y: -155.36,
                    z: 0,
                    child: GeneratedBuuton2Widget4()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 10.02,
                    y: -296.00,
                    z: 0,
                    child: GeneratedStatusbarWidget7()),
              )
            ]),
      ),
    ));
  }
}
