import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedEntry_linesWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedCreatebackWidget1.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedStatusbarWidget6.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedTcWidget1.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedIphonekeyboard1Widget1.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_screenwidget/generated/GeneratedBack_loginWidget1.dart';

/* Component login_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 641.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 94.0,
                                    height: 32.0,
                                    child: TransformHelper.translate(
                                        x: -116.00,
                                        y: -244.00,
                                        z: 0,
                                        child: GeneratedCreatebackWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 324.0,
                                    height: 106.0,
                                    child: TransformHelper.translate(
                                        x: 3.00,
                                        y: -154.00,
                                        z: 0,
                                        child: GeneratedEntry_linesWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 247.0,
                                    height: 41.87214660644531,
                                    child: TransformHelper.translate(
                                        x: 4.50,
                                        y: -11.06,
                                        z: 0,
                                        child: GeneratedButtonWidget2()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 124.0,
                                    height: 19.0,
                                    child: TransformHelper.translate(
                                        x: -92.00,
                                        y: -69.50,
                                        z: 0,
                                        child: GeneratedTcWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 179.0,
                                    height: 16.0,
                                    child: TransformHelper.translate(
                                        x: 5.50,
                                        y: 40.00,
                                        z: 0,
                                        child: GeneratedBack_loginWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 292.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: 175.00,
                                        z: 0,
                                        child:
                                            GeneratedIphonekeyboard1Widget1()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 1.02,
                  y: -296.00,
                  z: 0,
                  child: GeneratedStatusbarWidget6()),
            )
          ]),
    ));
  }
}
