import 'package:flutter/material.dart';

/* Component splash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 247, 247, 247),
          ),
        ),
      ),
    ));
  }
}
