import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen5widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen5widget/generated/GeneratedPagesbuttonWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen5widget/generated/GeneratedIcsharpnextweekWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen5widget/generated/GeneratedEasyFindingsCitationsandRatiosmadeeasytofindCaseFilesha.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen5widget/generated/GeneratedStatusbarWidget.dart';

/* Component welcome_screen5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome_screen5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedLogin_platformsWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 640.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 360.0,
                              height: 640.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 247, 247, 247),
                                      ),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 255.2581787109375,
                                      height: 202.0,
                                      child: TransformHelper.translate(
                                          x: 6.63,
                                          y: 58.00,
                                          z: 0,
                                          child:
                                              GeneratedEasyFindingsCitationsandRatiosmadeeasytofindCaseFilesha()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 50.0,
                                      height: 50.0,
                                      child: TransformHelper.translate(
                                          x: 1.00,
                                          y: 210.00,
                                          z: 0,
                                          child:
                                              GeneratedIcsharpnextweekWidget()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 250.00006103515625,
                                      height: 210.0,
                                      child: TransformHelper.translate(
                                          x: -11.00,
                                          y: -120.00,
                                          z: 0,
                                          child: GeneratedSearchWidget()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 232.0,
                                      height: 18.0,
                                      child: TransformHelper.translate(
                                          x: -11.00,
                                          y: 148.00,
                                          z: 0,
                                          child: GeneratedPagesbuttonWidget()),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 1.02,
                    y: -296.00,
                    z: 0,
                    child: GeneratedStatusbarWidget()),
              )
            ]),
      ),
    ));
  }
}
