import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedStatusbarWidget4.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedIcsharpnextweekWidget4.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedPagesbuttonWidget4.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedTheCourtofAppealReportsisamustreadforallJudgesLegalPrac.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen1widget/generated/GeneratedGroup2Widget.dart';

/* Component welcome_screen1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome_screen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedWelcome_screen2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 640.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 360.0,
                              height: 640.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 247, 247, 247),
                                      ),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 250.0000457763672,
                                      height: 216.0,
                                      child: TransformHelper.translate(
                                          x: 4.00,
                                          y: -138.00,
                                          z: 0,
                                          child: GeneratedGroup2Widget()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 300.260009765625,
                                      height: 202.0,
                                      child: TransformHelper.translate(
                                          x: 5.13,
                                          y: 39.00,
                                          z: 0,
                                          child:
                                              GeneratedTheCourtofAppealReportsisamustreadforallJudgesLegalPrac()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 232.0,
                                      height: 18.0,
                                      child: TransformHelper.translate(
                                          x: -1.00,
                                          y: 151.00,
                                          z: 0,
                                          child: GeneratedPagesbuttonWidget4()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 50.0,
                                      height: 50.0,
                                      child: TransformHelper.translate(
                                          x: 1.00,
                                          y: 210.00,
                                          z: 0,
                                          child:
                                              GeneratedIcsharpnextweekWidget4()),
                                    ),
                                    Positioned(
                                      left: null,
                                      top: null,
                                      right: null,
                                      bottom: null,
                                      width: 230.0,
                                      height: 46.21210479736328,
                                      child: TransformHelper.translate(
                                          x: 0.00,
                                          y: 277.11,
                                          z: 0,
                                          child: GeneratedButtonWidget()),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 10.02,
                    y: -296.00,
                    z: 0,
                    child: GeneratedStatusbarWidget4()),
              )
            ]),
      ),
    ));
  }
}
