import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen2widget/generated/GeneratedPagesbuttonWidget3.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen2widget/generated/GeneratedStatusbarWidget3.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen2widget/generated/GeneratedIcsharpnextweekWidget3.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen2widget/generated/GeneratedCarelectronicWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedwelcome_screen2widget/generated/GeneratedElectronicCourtOFAppealReportsOver1000copiesoftheElectr.dart';

/* Component welcome_screen2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome_screen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 640.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 255.2581787109375,
                                    height: 202.0,
                                    child: TransformHelper.translate(
                                        x: 5.63,
                                        y: 44.00,
                                        z: 0,
                                        child:
                                            GeneratedElectronicCourtOFAppealReportsOver1000copiesoftheElectr()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 50.0,
                                    height: 50.0,
                                    child: TransformHelper.translate(
                                        x: 1.00,
                                        y: 210.00,
                                        z: 0,
                                        child:
                                            GeneratedIcsharpnextweekWidget3()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 200.0,
                                    child: TransformHelper.translate(
                                        x: -7.00,
                                        y: -141.00,
                                        z: 0,
                                        child: GeneratedCarelectronicWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 232.0,
                                    height: 18.0,
                                    child: TransformHelper.translate(
                                        x: 8.00,
                                        y: 143.00,
                                        z: 0,
                                        child: GeneratedPagesbuttonWidget3()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 10.02,
                  y: -296.00,
                  z: 0,
                  child: GeneratedStatusbarWidget3()),
            )
          ]),
    ));
  }
}
