import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedGoogle_loginWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedCOURTOFAPPEALREPORTSNIGERIAWidget1.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedStatusbarWidget10.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedLogin_textWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedCREATEACCOUNTWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedlogin_platformswidget/generated/GeneratedFacebook_loginWidget.dart';

/* Component login_platforms
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_platformsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 640.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 252.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: -194.00,
                                        z: 0,
                                        child: GeneratedRectangle2Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 415.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: 107.50,
                                        z: 0,
                                        child: GeneratedRectangle1Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 279.0,
                                    height: 184.0,
                                    child: TransformHelper.translate(
                                        x: -6.50,
                                        y: -103.00,
                                        z: 0,
                                        child: GeneratedLogin_textWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 215.1292724609375,
                                    height: 30.87860107421875,
                                    child: TransformHelper.translate(
                                        x: 2.56,
                                        y: -222.44,
                                        z: 0,
                                        child:
                                            GeneratedCOURTOFAPPEALREPORTSNIGERIAWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 297.0,
                                    height: 50.0,
                                    child: TransformHelper.translate(
                                        x: 7.50,
                                        y: 29.00,
                                        z: 0,
                                        child: GeneratedGoogle_loginWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 297.0,
                                    height: 50.0,
                                    child: TransformHelper.translate(
                                        x: 7.50,
                                        y: 96.00,
                                        z: 0,
                                        child: GeneratedFacebook_loginWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 303.0,
                                    height: 1.0,
                                    child: TransformHelper.translate(
                                        x: 4.50,
                                        y: 293.50,
                                        z: 0,
                                        child: GeneratedLine3Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 89.0,
                                    height: 33.0,
                                    child: TransformHelper.translate(
                                        x: -3.50,
                                        y: 178.50,
                                        z: 0,
                                        child: GeneratedORWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 141.0,
                                    height: 26.0,
                                    child: TransformHelper.translate(
                                        x: -3.50,
                                        y: 218.00,
                                        z: 0,
                                        child: GeneratedCREATEACCOUNTWidget()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 2.02,
                  y: -291.00,
                  z: 0,
                  child: GeneratedStatusbarWidget10()),
            )
          ]),
    ));
  }
}
