import 'package:flutter/material.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedMenubarWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedRecentlyreadWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedExploreWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedForYouWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedStatusbarWidget8.dart';
import 'package:flutterapp/carappenuguapp/generatedhome_screenwidget/generated/GeneratedEllipse48Widget.dart';

/* Component home_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 640.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 81.0,
                                    height: 1.0,
                                    child: TransformHelper.translate(
                                        x: -121.50,
                                        y: -246.00,
                                        z: 0,
                                        child: GeneratedLine6Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 159.0,
                                    height: 112.39659118652344,
                                    child: TransformHelper.translate(
                                        x: -77.50,
                                        y: -161.13,
                                        z: 0,
                                        child: GeneratedRectangle6Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 154.99998474121094,
                                    height: 110.09385681152344,
                                    child: TransformHelper.translate(
                                        x: -67.50,
                                        y: -163.95,
                                        z: 0,
                                        child: GeneratedRectangle7Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 142.0,
                                    height: 58.0,
                                    child: TransformHelper.translate(
                                        x: 79.00,
                                        y: -172.00,
                                        z: 0,
                                        child: GeneratedGroup1Widget()),
                                  ),

                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 37.0,
                                    height: 37.0,
                                    child: TransformHelper.translate(
                                        x: 148.50,
                                        y: -258.50,
                                        z: 0,
                                        child: GeneratedEllipse48Widget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 67.0,
                                    height: 31.0,
                                    child: TransformHelper.translate(
                                        x: -29.50,
                                        y: -261.50,
                                        z: 0,
                                        child: GeneratedExploreWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 84.0,
                                    height: 35.0,
                                    child: TransformHelper.translate(
                                        x: -120.00,
                                        y: -262.50,
                                        z: 0,
                                        child: GeneratedForYouWidget()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 10.02,
                  y: -296.00,
                  z: 0,
                  child: GeneratedStatusbarWidget8()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 369.0,
              height: 65.0,
              child: TransformHelper.translate(
                  x: -4.50, y: 261.50, z: 0, child: GeneratedMenubarWidget()),
            )
          ]),
    ));
  }
}
