import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedreadscreenwidget/generated/GeneratedReptabWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedreadscreenwidget/generated/GeneratedMenu2Widget1.dart';
import 'package:flutterapp/carappenuguapp/generatedreadscreenwidget/generated/GeneratedStatusbarWidget9.dart';

/* Component readscreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReadscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 923.040771484375,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 521.9996337890625,
                                    height: 886.040771484375,
                                    child: TransformHelper.translate(
                                        x: 42.00,
                                        y: 160.02,
                                        z: 0,
                                        child: GeneratedReptabWidget()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 10.02,
                  y: -296.00,
                  z: 0,
                  child: GeneratedStatusbarWidget9()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 351.0,
              height: 108.0,
              child: TransformHelper.translate(
                  x: -4.50, y: 282.00, z: 0, child: GeneratedMenu2Widget1()),
            )
          ]),
    ));
  }
}
