import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedStatusbarWidget5.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedCreatebackWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedBack_loginWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedEntry_linesWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedTcWidget.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/carappenuguapp/generatedregister_screenwidget/generated/GeneratedIphonekeyboard1Widget.dart';

/* Component register_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegister_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 640.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 640.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 196.0,
                                    height: 32.0,
                                    child: TransformHelper.translate(
                                        x: -65.00,
                                        y: -244.00,
                                        z: 0,
                                        child: GeneratedCreatebackWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 324.0,
                                    height: 106.0,
                                    child: TransformHelper.translate(
                                        x: 3.00,
                                        y: -154.00,
                                        z: 0,
                                        child: GeneratedEntry_linesWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 247.0,
                                    height: 43.0,
                                    child: TransformHelper.translate(
                                        x: 4.50,
                                        y: -10.50,
                                        z: 0,
                                        child: GeneratedButtonWidget1()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 299.0,
                                    height: 37.0,
                                    child: TransformHelper.translate(
                                        x: -3.50,
                                        y: -61.50,
                                        z: 0,
                                        child: GeneratedTcWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 179.0,
                                    height: 16.0,
                                    child: TransformHelper.translate(
                                        x: 5.50,
                                        y: 39.00,
                                        z: 0,
                                        child: GeneratedBack_loginWidget()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 364.0,
                                    height: 287.0,
                                    child: TransformHelper.translate(
                                        x: -2.00,
                                        y: 176.50,
                                        z: 0,
                                        child:
                                            GeneratedIphonekeyboard1Widget()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 1.02,
                  y: -296.00,
                  z: 0,
                  child: GeneratedStatusbarWidget5()),
            )
          ]),
    ));
  }
}
